'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Route,CalendarDays,Plane,MapPin,ChevronRight,Clock3,Footprints,TrainFront,Utensils,Landmark,ShoppingBag,Coffee,ArrowUpRight,Maximize2,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {days,places,type Place} from './trip';
const kinds:Record<string,typeof MapPin>={food:Utensils,sight:Landmark,shop:ShoppingBag,cafe:Coffee,station:TrainFront,airport:Plane};
const google=(p:Place)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.jp+' '+p.address)}`;
const directions=(p:Place,prev?:Place,mode='transit')=>`https://www.google.com/maps/dir/?api=1&${prev?'origin='+encodeURIComponent(prev.jp+' '+prev.address)+'&':''}destination=${encodeURIComponent(p.jp+' '+p.address)}&travelmode=${mode}`;
let leaflet:Promise<any>|undefined;
function loadMap(){if(!leaflet)leaflet=new Promise((resolve,reject)=>{const w=window as any;if(w.L)return resolve(w.L);const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';css.integrity='sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=';css.crossOrigin='';document.head.appendChild(css);const js=document.createElement('script');js.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';js.integrity='sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=';js.crossOrigin='';js.onload=()=>resolve(w.L);js.onerror=()=>{leaflet=undefined;reject(new Error('map unavailable'))};document.head.appendChild(js)});return leaflet}
export default function Home(){
 const [dayIndex,setDayIndex]=useState(0),[selected,setSelected]=useState(''),[ready,setReady]=useState(false),[error,setError]=useState(false),[wide,setWide]=useState(false),[overview,setOverview]=useState(false);
 const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),lib=useRef<any>(null),layer=useRef<any>(null),pins=useRef<Record<string,any>>({}),fit=useRef(()=>{}),current=useRef(0);current.current=dayIndex;
 const day=days[dayIndex];const choice=day.stops.find(s=>s.id===selected);const place=choice?places[choice.place]:null;
 function changeDay(i:number){setDayIndex(i);setSelected('');setWide(false);setOverview(false);window.history.replaceState(null,'',`#day-${i+1}`)}
 useEffect(()=>{const n=Number(location.hash.match(/^#day-([1-4])$/)?.[1]);if(n)setDayIndex(n-1);let dead=false;loadMap().then(L=>{if(dead||!el.current)return;lib.current=L;map.current=L.map(el.current,{zoomControl:false}).setView([34.68,135.505],13);L.control.zoom({position:'topright'}).addTo(map.current);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'});let failed=0;tiles.on('tileerror',()=>{if(++failed>5)setError(true)});tiles.on('tileload',()=>{failed=0;setError(false)});tiles.addTo(map.current);layer.current=L.layerGroup().addTo(map.current);setReady(true)}).catch(()=>{if(!dead)setError(true)});return()=>{dead=true;map.current?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready||!map.current)return;layer.current.clearLayers();pins.current={};const shown=overview?days:[day];const bounds:number[][]=[];shown.forEach(d=>{const stops=d.stops.filter(s=>wide||places[s.place].kind!=='airport');const pts=stops.map(s=>places[s.place].coords);bounds.push(...pts);if(pts.length>1){lib.current.polyline(pts,{color:'#fff',weight:7,opacity:.96}).addTo(layer.current);lib.current.polyline(pts,{color:d.color,weight:3,dashArray:'6 9',opacity:.9}).addTo(layer.current)}stops.forEach(s=>{const p=places[s.place],n=d.stops.indexOf(s)+1;const icon=lib.current.divIcon({className:'route-marker',html:`<span style="background:${d.color}">${n}</span>`,iconSize:[34,34],iconAnchor:[17,17]});const marker=lib.current.marker(p.coords,{icon,title:`${d.shortDate} ${n}. ${p.name}`,keyboard:true}).addTo(layer.current);marker.bindTooltip(p.name,{direction:'top',offset:[0,-15]});marker.on('click',()=>{if(overview){setDayIndex(days.indexOf(d));setOverview(false)}setSelected(s.id);setTimeout(()=>document.getElementById(s.id)?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)});pins.current[s.id]=marker})});fit.current=()=>{if(bounds.length&&map.current)map.current.fitBounds(bounds,{padding:[45,55],maxZoom:15,animate:false})};fit.current();const resize=new ResizeObserver(()=>map.current?.invalidateSize());if(el.current)resize.observe(el.current);return()=>resize.disconnect()},[dayIndex,ready,wide,overview]);
 useEffect(()=>{if(!place||!map.current)return;if(place.kind==='airport'&&!wide)setWide(true);map.current.flyTo(place.coords,15,{duration:.5});Object.entries(pins.current).forEach(([id,p])=>p.getElement()?.classList.toggle('is-selected',id===selected))},[selected,wide]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();const register=(t:any)=>{try{Promise.resolve(ctx.registerTool(t,{signal:c.signal})).catch(()=>{})}catch{}};register({name:'get_osaka_itinerary',description:'Read the September 14–17 itinerary and currently selected day.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({selectedDay:current.current+1,days:days.map(d=>({date:d.date,stops:d.stops.map(s=>({id:s.id,name:places[s.place].name,time:s.time}))}))})});register({name:'show_osaka_day',description:'Show one travel day in the schedule and map.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:4}},required:['day'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!Number.isInteger(input?.day)||input.day<1||input.day>4)throw new Error('day must be 1–4');flushSync(()=>changeDay(input.day-1));return{date:days[input.day-1].date}}});return()=>c.abort()},[]);
 return <main><header className="topbar"><a href="#day-1" onClick={()=>changeDay(0)} className="brand"><span><Route size={23}/></span>나의 오사카<small>TRIP NOTES</small></a><div className="dates"><CalendarDays size={16}/>2026.09.14 — 09.17<b>3박 4일</b></div></header>
 <div className="workspace"><aside className="itinerary"><section className="cover"><img src="./osaka.jpg" width="1280" height="853" alt="글리코 간판과 네온사인이 빛나는 도톤보리의 밤"/><div><span>JAPAN · OSAKA</span><h1>맛있는 오사카,<br/>천천히 걷는 4일.</h1><p>성곽 산책부터 도톤보리의 밤까지</p></div></section><div className="flights"><span><Plane size={16}/><small>가는 날</small><b>14일 09:40</b></span><i/><span><Plane size={16}/><small>오는 날</small><b>17일 16:00</b></span></div>
 <Tabs value={String(dayIndex)} onValueChange={v=>changeDay(Number(v))} className="day-tabs"><TabsList className="day-tab-list" aria-label="여행 날짜">{days.map((d,i)=><TabsTrigger key={d.date} value={String(i)} className="day-tab"><span>{d.shortDate}<small>{d.weekday}</small></span><b>DAY {i+1}</b></TabsTrigger>)}</TabsList>
 {days.map((d,i)=><TabsContent key={d.date} value={String(i)} className="day-panel"><div className="day-heading"><div><p className="eyebrow">DAY {i+1}<span> · {d.stops.length}개 일정</span></p><h2>{d.title}</h2><p>{d.area}</p></div><span className="day-icon" style={{color:d.color}}><Route size={25}/></span></div><div className="day-note"><Clock3 size={16}/><p>{d.note}</p></div>
 <ol className="timeline">{d.stops.map((s,n)=>{const p=places[s.place],Icon=kinds[p.kind],prev=n?places[d.stops[n-1].place]:undefined;return <li key={s.id} id={s.id} className={selected===s.id?'stop selected':'stop'}>{n>0&&<div className="transfer">{s.mode==='walking'?<Footprints size={14}/>:<TrainFront size={14}/>}<span>{s.transfer}</span><a href={directions(p,prev,s.mode)} target="_blank" rel="noreferrer" aria-label={`${prev?.name}에서 ${p.name}까지 길찾기`}><ArrowUpRight size={14}/></a></div>}<div className="stop-row"><span className="number" style={{background:d.color}}>{n+1}</span><div className="stop-body"><button className="stop-main" aria-expanded={selected===s.id} onClick={()=>setSelected(selected===s.id?'':s.id)}><span className="stop-meta"><span className={`kind ${p.kind}`}><Icon size={13}/>{s.label}</span><time>{s.time}</time></span><span className="stop-title">{p.name}<ChevronRight size={17}/></span><span className="summary">{s.summary}</span></button>{selected===s.id&&<div className="detail"><p className="jp">{p.jp}</p><p>{p.description}</p><p className="address"><MapPin size={14}/>{p.address}</p>{p.hours&&<p className="address"><Clock3 size={14}/>{p.hours}</p>}{s.note&&<p className="place-note">{s.note}</p>}<div className="actions"><a href={google(p)} target="_blank" rel="noreferrer"><MapPin size={14}/>구글 지도</a><a href={directions(p,prev,s.mode)} target="_blank" rel="noreferrer"><Route size={14}/>길찾기</a>{p.source&&<a href={p.source} target="_blank" rel="noreferrer">안내<ExternalLink size={12}/></a>}</div></div>}</div></div></li>})}</ol>
 <div className="day-footer"><p>방문 시간과 이동 시간은 대략적인 계획이에요.</p>{i<3&&<button onClick={()=>changeDay(i+1)}>다음 날 보기<ChevronRight size={16}/></button>}</div></TabsContent>)}</Tabs>
 <footer className="credits"><p>방문 정보 확인 · 2026.09.06</p><p>사진 <a href="https://commons.wikimedia.org/wiki/File:D%C5%8Dtonbori_at_night,_Osaka_(19551420339).jpg" target="_blank" rel="noreferrer">Kristoffer Trolle</a> · <a href="https://creativecommons.org/licenses/by/2.0/" target="_blank" rel="noreferrer">CC BY 2.0</a> · 화면에 맞게 크롭</p></footer></aside>
 <section className="map-panel" aria-label="여행 동선 지도"><div className="map" ref={el}/><div className="map-top"><div className="map-label"><i style={{background:overview?'#244456':day.color}}/><b>{overview?'4일 전체 동선':`${day.shortDate} ${day.weekday}요일 동선`}</b></div><button className={overview?'overview active':'overview'} onClick={()=>{setOverview(!overview);setSelected('');setWide(false)}}>여행 전체<Maximize2 size={15}/></button></div>{!ready&&!error&&<div className="loading"><Route size={25}/><p>오사카 지도를 불러오는 중</p></div>}{error&&<div className="map-error">지도 연결이 원활하지 않아요. 일정 카드의 구글 지도에서 위치와 길찾기를 확인할 수 있어요.</div>}{overview&&<div className="legend">{days.map((d,i)=><button key={d.date} onClick={()=>changeDay(i)}><i style={{background:d.color}}/><b>{d.shortDate}</b>{d.area}</button>)}</div>}
 <div className="map-bottom">{place&&!overview&&<div className="map-place"><span className="place-icon" style={{color:day.color}}><MapPin size={24}/></span><div><span>{choice?.time} · {choice?.label}</span><h3>{place.name}</h3></div><a href={google(place)} target="_blank" rel="noreferrer" aria-label={`${place.name} 구글 지도`}><ArrowUpRight size={23}/></a></div>}<div className="map-controls"><button onClick={()=>fit.current()}><Maximize2 size={15}/>동선 한눈에</button><button onClick={()=>{setWide(!wide);setSelected('')}}>{wide?'시내 중심으로':'공항 구간 포함'}</button></div><p className="disclaimer">위치는 참고용 · 점선은 방문 순서예요. 실제 경로는 길찾기에서 확인하세요.</p></div></section></div></main>
}
